### ISSUE TITLE
Chat button on product page

### ISSUE THREAD

**Issue by andreapiccin** [skupply/frontend#18]
Nella procedura non si tiene conto dell'eventuale esistenza della chat prima di crearla.
Una volta creata / trovata il bottone deve rimandare direttamente alla pagina con la chat aperta, non solo alla lista dei contatti

**Comment by najirod02** [comment]
in teoria anche premendo il pulsante, non crea una nuova chat se già presente.

**Comment by andreapiccin** [comment]
> in teoria anche premendo il pulsante, non crea una nuova chat se già presente.

si, corretto.
È possibile fixare anche il secondo punto?

**Comment by najirod02** [comment]
forse passando nell'url lo username si potrebbe verificare quale card contatto ha quello username e chiamare direttamente la funzione per aprire la chat, tipo un fireEvent su java
