### ISSUE TITLE
Cart bug

### ISSUE THREAD

**Issue by andreapiccin** [skupply/frontend#25]
Se:
1- Si aggiungono due prodotti al carrello
2- si elimina il primo
3- si procede al checkout
succede che si effettua l'ordine del primo prodotto (eliminato) al prezzo del secondo.
Sospetto che non venga aggiornato l'array dei prodotti dopo la rimozione di uno (probabilmente si chiama la API che aggiorna i dati remoti ma non si aggiornano gli array locali).

**Comment by najirod02** [comment]
fixed, al posto di id avevo scritto _id
