### ISSUE TITLE
Modify article in draft

### ISSUE THREAD

**Issue by najirod02** [skupply/frontend#39]
Modificando l'annunci nella sezione bozze e premendo il pulsante salva, si va in caricamento infinito e in console viene dato errore.
( cannot read label )
il valore di label è undefined, probabilmente viene dichiarata la variabile ma non il suo valore.

![image](https://user-images.githubusercontent.com/106140800/218271532-83b5743d-a0f2-40f3-982e-db72a49ef304.png)

**Comment by ghost** [comment]
Fixato, il problema si verificava quando un prodotto non aveva una categoria. Adesso se non ha una categoria gli viene assegnata la prima disponibile (Nuovo)
